

variables:
  REGISTRY_GROUP_PROJECT: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME

stages:
  - build
  - release

build:
  stage: build
  image: maven:3-openjdk-17
  only:
    - master
  script:
    - mvn -DskipTests=true clean package

release:
  stage: release
  image: paketobuildpacks/builder
  before_script:
    - mkdir ~/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_JOB_TOKEN\"}}}" >> ~/.docker/config.json  
  script:
    - /cnb/lifecycle/creator -app . -cache-image $REGISTRY_GROUP_PROJECT/paketo-build-cache:latest $REGISTRY_GROUP_PROJECT:latest
  rules:
    # Only publish if tag given
    - if: '$CI_COMMIT_TAG'

